"""Loss-resistant, provenance-linked context compilation for long-running agents."""

from .archive import (
    ARCHIVE_ENTRY_SCHEMA,
    ARCHIVE_GENESIS_SHA256,
    ARCHIVE_REPORT_SCHEMA,
    LEGACY_ARCHIVE_SCHEMA,
    ArchiveReport,
    SourceArchive,
)
from .artifact_diff import ARTIFACT_DIFF_SCHEMA, diff_artifacts
from .artifact_inspection import (
    ARTIFACT_INSPECTION_SCHEMA,
    render_artifact_text,
    summarize_artifact,
)
from .compiler import ContextCompiler
from .connector import (
    CONNECTOR_INSPECTION_SCHEMA,
    CONNECTOR_OPERATIONS,
    CONNECTOR_PROTOCOL_VERSION,
    CONNECTOR_REQUEST_SCHEMA,
    CONNECTOR_RESPONSE_SCHEMA,
    CONTEXT_BUNDLE_SCHEMA,
    INCREMENTAL_CHECKPOINT_SCHEMA,
    RETENTION_CERTIFICATE_WORDING,
    SOURCE_EVENT_SCHEMA,
    ContextBundle,
    ExactTokenCounterAdapter,
    IncrementalCompiler,
    LocalAIConnector,
    SourceEvent,
    decode_connector_request,
    serve_stdio,
    source_event_to_record,
)
from .context_window import ContextWindowBudget
from .extractors import (
    CompositeExtractor,
    DomainLabelExtractor,
    ExtractionResult,
    Extractor,
    LiteralModelExtractor,
    ModelExtractor,
    RuleBasedExtractor,
)
from .io import validate_artifact_envelope
from .isolation import CompilationIsolationError
from .limits import (
    ArtifactLimitError,
    ArtifactLimits,
    CompilationLimitError,
    CompilationLimits,
    SourceLimitError,
    SourceLimits,
)
from .local_qwen import LmsQwenCompletion, LocalQwenError
from .materialized_window import (
    MATERIALIZED_CONTEXT_COMPONENTS_SCHEMA,
    MATERIALIZED_CONTEXT_RECEIPT_SCHEMA,
    MATERIALIZED_CONTEXT_RESULT_SCHEMA,
    materialize_context,
    verify_materialized_context_result,
)
from .models import (
    COMPILATION_METRICS_SCHEMA,
    MAX_SOURCE_ID_CHARS,
    MAX_SOURCE_ROLE_CHARS,
    MAX_SOURCE_TIMESTAMP_CHARS,
    CompilationMetrics,
    CompilationPolicy,
    CompiledMemory,
    MemoryItem,
    MemoryKind,
    MemoryStatus,
    ProvenanceSpan,
    SourceRecord,
    VerificationReport,
)
from .path_safety import PathBoundaryError
from .redaction import (
    REDACTION_REPORT_SCHEMA,
    REDACTION_VERIFICATION_SCHEMA,
    SECRET_DETECTOR_NAMES,
    RedactionError,
    RedactionFinding,
    RedactionLimitError,
    RedactionPolicy,
    RedactionResult,
    redact_sources,
    verify_redaction_report_hash,
    verify_redaction_result,
)
from .schema_compatibility import (
    ARTIFACT_SCHEMA_COMPATIBILITY_SCHEMA,
    artifact_schema_registry,
    artifact_schema_support,
)
from .trust import (
    TRUST_MANIFEST_SCHEMA,
    TRUST_VERIFICATION_SCHEMA,
    TrustManifestError,
    create_trust_manifest,
    load_trust_manifest,
    load_trust_manifest_path,
    trust_manifest_sha256,
    validate_trust_manifest,
    verify_trust_manifest,
)

__all__ = [
    "ARCHIVE_ENTRY_SCHEMA",
    "ARCHIVE_GENESIS_SHA256",
    "ARCHIVE_REPORT_SCHEMA",
    "ArchiveReport",
    "ArtifactLimitError",
    "ArtifactLimits",
    "ARTIFACT_DIFF_SCHEMA",
    "ARTIFACT_INSPECTION_SCHEMA",
    "ARTIFACT_SCHEMA_COMPATIBILITY_SCHEMA",
    "COMPILATION_METRICS_SCHEMA",
    "CONNECTOR_INSPECTION_SCHEMA",
    "CONNECTOR_OPERATIONS",
    "CONNECTOR_PROTOCOL_VERSION",
    "CONNECTOR_REQUEST_SCHEMA",
    "CONNECTOR_RESPONSE_SCHEMA",
    "CONTEXT_BUNDLE_SCHEMA",
    "MATERIALIZED_CONTEXT_COMPONENTS_SCHEMA",
    "MATERIALIZED_CONTEXT_RECEIPT_SCHEMA",
    "MATERIALIZED_CONTEXT_RESULT_SCHEMA",
    "MAX_SOURCE_ID_CHARS",
    "MAX_SOURCE_ROLE_CHARS",
    "MAX_SOURCE_TIMESTAMP_CHARS",
    "CompilationIsolationError",
    "CompilationLimitError",
    "CompilationLimits",
    "CompilationMetrics",
    "CompilationPolicy",
    "CompiledMemory",
    "CompositeExtractor",
    "ContextCompiler",
    "ContextBundle",
    "ContextWindowBudget",
    "DomainLabelExtractor",
    "ExtractionResult",
    "Extractor",
    "ExactTokenCounterAdapter",
    "INCREMENTAL_CHECKPOINT_SCHEMA",
    "IncrementalCompiler",
    "MemoryItem",
    "MemoryKind",
    "MemoryStatus",
    "ModelExtractor",
    "PathBoundaryError",
    "LmsQwenCompletion",
    "LocalQwenError",
    "LiteralModelExtractor",
    "LocalAIConnector",
    "LEGACY_ARCHIVE_SCHEMA",
    "ProvenanceSpan",
    "REDACTION_REPORT_SCHEMA",
    "REDACTION_VERIFICATION_SCHEMA",
    "RETENTION_CERTIFICATE_WORDING",
    "RedactionError",
    "RedactionFinding",
    "RedactionLimitError",
    "RedactionPolicy",
    "RedactionResult",
    "RuleBasedExtractor",
    "SECRET_DETECTOR_NAMES",
    "SOURCE_EVENT_SCHEMA",
    "SourceArchive",
    "SourceLimitError",
    "SourceLimits",
    "SourceRecord",
    "SourceEvent",
    "TRUST_MANIFEST_SCHEMA",
    "TRUST_VERIFICATION_SCHEMA",
    "TrustManifestError",
    "VerificationReport",
    "artifact_schema_registry",
    "artifact_schema_support",
    "create_trust_manifest",
    "decode_connector_request",
    "diff_artifacts",
    "load_trust_manifest",
    "load_trust_manifest_path",
    "materialize_context",
    "render_artifact_text",
    "redact_sources",
    "summarize_artifact",
    "serve_stdio",
    "source_event_to_record",
    "trust_manifest_sha256",
    "validate_artifact_envelope",
    "validate_trust_manifest",
    "verify_redaction_report_hash",
    "verify_redaction_result",
    "verify_materialized_context_result",
    "verify_trust_manifest",
]

__version__ = "0.1.1a4"
